### Load the libraries needed

In [1]:
from sklearn.svm import SVC
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn import datasets

### Load the data

In [2]:
df = datasets.load_iris(as_frame=True).frame
df.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0

### Information about data

In [3]:
# describe function to get numerical info about data
df.describe()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
count,150.000000,150.000000,150.000000,150.000000,150.000000
mean,5.843333,3.057333,3.758000,1.199333,1.000000
std,0.828066,0.435866,1.765298,0.762238,0.819232
min,4.300000,2.000000,1.000000,0.100000,0.000000
25%,5.100000,2.800000,1.600000,0.300000,0.000000
50%,5.800000,3.000000,4.350000,1.300000,1.000000
75%,6.400000,3.300000,5.100000,1.800000,2.000000
max,7.900000,4.400000,6.900000,2.500000,2.000000

In [4]:
# information about the data
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    float64
 3   petal width (cm)   150 non-null    float64
 4   target             150 non-null    int64
dtypes: float64(4), int64(1)
memory usage: 6.0 KB

In [5]:
# check number of null values
df.isnull().sum()

sepal length (cm)    0
sepal width (cm)     0
petal length (cm)    0
petal width (cm)     0
target               0
dtype: int64

### Split the data into training and testing part

In [6]:
# dependent variable
x = df.drop(columns=["target"])
x.head()

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [7]:
# independent variable
y = df["target"]
y.head()

0    0
1    0
2    0
3    0
4    0
Name: target, dtype: int64

In [8]:
# train test split
train_x, test_x, train_y, test_y = train_test_split(x, y, test_size=0.3, random_state = 42, stratify=y)

In [9]:
len(train_x), len(test_x), len(train_y), len(test_y)

(105, 45, 105, 45)

### Preprocessing data

In [10]:
# import standard scaler
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
train_x_scaled = scaler.fit_transform(train_x)
test_x_scaled = scaler.transform(test_x)

### Create and Evaluate Model

In [11]:
# create object
svc = SVC()

In [12]:
# create model
svc.fit(train_x_scaled, train_y)

SVC()

In [13]:
# predict
y_pred = svc.predict(test_x_scaled)
y_pred

array([2, 1, 1, 1, 2, 2, 1, 1, 0, 2, 0, 0, 2, 2, 0, 2, 1, 0, 0, 0, 1, 0,
       1, 2, 2, 1, 1, 1, 1, 0, 2, 2, 1, 0, 2, 0, 0, 0, 0, 2, 1, 0, 1, 2,
       1])

In [14]:
# Evaluate
from sklearn.metrics import accuracy_score, classification_report

print("accuracy: ", accuracy_score(test_y, y_pred))
print("classification: ", classification_report(test_y, y_pred))

accuracy:  0.9333333333333333
classification:                precision    recall  f1-score   support

           0       1.00      1.00      1.00        15
           1       0.88      0.93      0.90        15
           2       0.93      0.87      0.90        15

    accuracy                           0.93        45
   macro avg       0.93      0.93      0.93        45
weighted avg       0.93      0.93      0.93        45

In [15]:
# Linear kernel

# create model
svc = SVC(kernel="linear")
svc.fit(train_x_scaled, train_y)

# predict
y_pred = svc.predict(test_x_scaled)

# Evaluate
print("accuracy: ", accuracy_score(test_y, y_pred))

accuracy:  0.9111111111111111

In [16]:
# poly kernel

# create model
svc = SVC(kernel="poly")
svc.fit(train_x_scaled, train_y)

# predict
y_pred = svc.predict(test_x_scaled)

# Evaluate
print("accuracy: ", accuracy_score(test_y, y_pred))

accuracy:  0.8666666666666667

In [17]:
# sigmoid kernel

# create model
svc = SVC(kernel="sigmoid")
svc.fit(train_x_scaled, train_y)

# predict
y_pred = svc.predict(test_x_scaled)

# Evaluate
print("accuracy: ", accuracy_score(test_y, y_pred))

accuracy:  0.9111111111111111

### Hyper parameter tuneing

In [18]:
c_vals = [0.5, 1, 2, 3, 4, 5]

for c_val in c_vals:
    # create model
    svc = SVC(kernel="rbf", C=c_val)
    svc.fit(train_x_scaled, train_y)
    
    # predict
    y_pred = svc.predict(test_x_scaled)
    
    # Evaluate
    print("accuracy:", accuracy_score(test_y, y_pred), "for C :", c_val)

accuracy: 0.9111111111111111 for C : 0.5
accuracy: 0.9333333333333333 for C : 1
accuracy: 0.9111111111111111 for C : 2
accuracy: 0.9111111111111111 for C : 3
accuracy: 0.9333333333333333 for C : 4
accuracy: 0.9333333333333333 for C : 5